In [49]:
import pandas as pd

In [50]:
df = pd.read_csv('/content/drive/MyDrive/sppg.csv')
df = df.dropna(how='all')
df = df.reset_index(drop=True)
df.tail()

,No,Provinsi SPPG,Kab./Kota SPPG,Kecamatan SPPG,Kelurahan/Desa SPPG,Alamat SPPG,Nama SPPG
27635,27636.0,SUMATERA UTARA,KARO,TIGABINANGA,PERGENDANGEN,"SIMPANG PERGENDANGEN, KECAMATAN TIGA BINANGA,...",SPPG Karo Tiga Binaga Pergendangen
27636,27637.0,JAWA TIMUR,SIDOARJO,SIDOARJO,SIDOKARE,"Ruko Royal Palace, Blok N9, Jl. Sunandar Priy...",SPPG Sidoarjo Sidoarjo Sidokare
27637,27638.0,JAWA BARAT,KOTA BANDUNG,REGOL,CISEUREUH,"JL. PURI DAGO MAS UTAMA NO.65, RT 007/ RW 023",SPPG Kota Bandung Regol Ciseureuh
27638,27639.0,JAWA BARAT,KOTA BOGOR,TANAH SAREAL,SUKADAMAI,"Jl. Seremped Wetan, RT.04/RW.09, Sukadamai, K...",SPPG Kota Bogor Tanah Sareal Sukadamai
27639,27640.0,LAMPUNG,PRINGSEWU,PRINGSEWU,PRINGSEWU SELATAN,"Jl Kartini RT/RW:02/03, Pringsewu Selatan",SPPG Pringsewu Pringsewu Pringsewu Selatan 1

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27640 entries, 0 to 27639
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   No                   27640 non-null  float64
 1   Provinsi SPPG        27640 non-null  object
 2   Kab./Kota SPPG       27640 non-null  object
 3   Kecamatan SPPG       27640 non-null  object
 4   Kelurahan/Desa SPPG  27640 non-null  object
 5   Alamat SPPG          27640 non-null  object
 6   Nama SPPG            27640 non-null  object
dtypes: float64(1), object(6)
memory usage: 1.5+ MB

# Jumlah provinsi yang punya sppg seluruh indonesia
semua provinsi punya

In [52]:
df['Provinsi SPPG'] = df['Provinsi SPPG'].apply(
    lambda x: 'PAPUA' if "".join(str(x).split()) == 'PAPUA' else str(x).strip()
)
jumlah_provinsi_unique = df['Provinsi SPPG'].nunique()
list_provinsi =df['Provinsi SPPG'].unique()
print("Jumlah provinsi yang punya sppg: ", jumlah_provinsi_unique)
print("List provinsi yang punya sppg:")
for prov in list_provinsi:
  print(prov)

Jumlah provinsi yang punya sppg:  38
List provinsi yang punya sppg:
JAWA TENGAH
KALIMANTAN SELATAN
KEPULAUAN RIAU
JAWA BARAT
NUSA TENGGARA TIMUR
SUMATERA UTARA
SULAWESI TENGGARA
SULAWESI UTARA
DAERAH ISTIMEWA YOGYAKARTA
RIAU
JAWA TIMUR
SUMATERA SELATAN
ACEH
LAMPUNG
DKI JAKARTA
BANTEN
SUMATERA BARAT
KALIMANTAN BARAT
NUSA TENGGARA BARAT
PAPUA BARAT
BALI
SULAWESI BARAT
KALIMANTAN TENGAH
JAMBI
BENGKULU
KALIMANTAN TIMUR
SULAWESI SELATAN
MALUKU UTARA
PAPUA PEGUNUNGAN
PAPUA TENGAH
KEPULAUAN BANGKA BELITUNG
SULAWESI TENGAH
PAPUA BARAT DAYA
MALUKU
GORONTALO
PAPUA
KALIMANTAN UTARA
PAPUA SELATAN

# Jumlah kabupaten/kota yang punya sppg

mostly di papua justru yang belum ada

ada 16 kabupaten / kota yang belum punya sppg. yaitu:

Daftar 16 Kabupaten/Kota yang Belum Terdeteksi:

    Provinsi Papua Pegunungan:

        Kab. Pegunungan Bintang

        Kab. Tolikara

        Kab. Nduga

        Kab. Mamberamo Tengah

        Kab. Yalimo

    Provinsi Papua Tengah:

        Kab. Puncak

        Kab. Puncak Jaya

        Kab. Dogiyai

        Kab. Paniai

        Kab. Intan Jaya

    Provinsi Papua Selatan:

        Kab. Boven Digoel
        
    Provinsi Papua Barat Daya:

        Kab. Tambrauw

        Kab. Maybrat

    Wilayah Lainnya:

        Kab. Mamberamo Raya (Papua)

        Kab. Kepulauan Mentawai (Sumatera Barat)

        Kab. Mahakam Ulu (Kalimantan Timur)

In [53]:
jumlah_kabupaten_kota_unique = df['Kab./Kota SPPG'].nunique()
list_kabupaten_kota =df['Kab./Kota SPPG'].unique()
print("Jumlah kabupaten/kota yang punya sppg: ", jumlah_kabupaten_kota_unique)
print("List kabupaten/kota yang punya sppg:")
for kab in list_kabupaten_kota:
  print(kab)

Jumlah kabupaten/kota yang punya sppg:  498
List kabupaten/kota yang punya sppg:
 KEBUMEN
 TANAH LAUT
 KOTA BATAM
 CIANJUR
 KOTA KUPANG
 SIMALUNGUN
 SUKABUMI
 MUNA BARAT
 KOTA SURAKARTA
 KEPULAUAN SANGIHE
 KULON PROGO
 KAMPAR
 KLATEN
 MALANG
 OGAN KOMERING ILIR
 ACEH UTARA
 SIDOARJO
 GRESIK
 CILACAP
 KOTA PASURUAN
 BALANGAN
 BANJAR
 SAMPANG
 LAMPUNG TENGAH
 INDRAMAYU
 BOGOR
 KOTA ADM. JAKARTA UTARA
 KOTA METRO
 KOTA KENDARI
 KARANGANYAR
 KOTA SERANG
 LAMONGAN
 BLITAR
 PRINGSEWU
 PATI
 PESAWARAN
 WONOSOBO
 BANYUMAS
 NAGEKEO
 MADIUN
 PESISIR SELATAN
 KOTA PONTIANAK
 BANDUNG
 KOTA SEMARANG
 KETAPANG
 SUMEDANG
 TEGAL
 PACITAN
 PANDEGLANG
 LOMBOK TENGAH
 GUNUNGKIDUL
 KOTA BEKASI
 WAY KANAN
 JEMBER
 BANDUNG BARAT
 OGAN KOMERING ULU TIMUR
 ACEH TENGAH
 MAJALENGKA
 BREBES
 KUPANG
 MANOKWARI
 KOTA LUBUK LINGGAU
 GIANYAR
 JOMBANG
 KOTA CIMAHI
 PURWAKARTA
 MAMUJU
 PEKALONGAN
 KARO
 KOTA PALANGKA RAYA
 CIREBON
 KOTA SALATIGA
 JEPARA
 LAMPUNG TIMUR
 SERDANG BEDAGAI
  MUARO JAMBI
 GARUT
 KOTA PALEMBANG
 SUBANG
 WONOGIRI
 MOJOKERTO
 PAMEKASAN
 BONDOWOSO
 SERANG
 PEMALANG
 KOTA ADM. JAKARTA SELATAN
 KOTA PADANG
 KOTA MEDAN
 BOYOLALI
 KOTA BENGKULU
 BLORA
 KUNINGAN
 KUTAI KARTANEGARA
 BEKASI
 TANGERANG
 KOTA BINJAI
 KUBU RAYA
 KOTA DEPOK
 KOTA PEKALONGAN
 BOJONEGORO
 JENEPONTO
 KOTA TERNATE
 LINGGA
 SIKKA
 BIMA
 KOTA YOGYAKARTA
 NGANJUK
 PADANG PARIAMAN
 KOTA PAREPARE
 SUKOHARJO
 LOMBOK UTARA
 JAYAWIJAYA
 LAMPUNG SELATAN
 KOTA BANDUNG
 HALMAHERA UTARA
 TULANG BAWANG BARAT
 ACEH TAMIANG
 TANJUNG JABUNG TIMUR
 BENGKULU UTARA
 KOTA SURABAYA
 PASURUAN
 LEBAK
 SRAGEN
 PURWOREJO
 LANNY JAYA
 MIMIKA
 MALAKA
 KONAWE
 KOTA TASIKMALAYA
 OGAN KOMERING ULU SELATAN
 ACEH BESAR
 DAIRI
 TABANAN
 MAGETAN
 KARAWANG
 ASAHAN
 PADANG LAWAS UTARA
 PURBALINGGA
 KEDIRI
 BARITO SELATAN
 KOTA TANGERANG SELATAN
 LOMBOK BARAT
 HULU SUNGAI TENGAH
 KOTA PANGKAL PINANG
 KOTA BOGOR
 BANJARNEGARA
 SLEMAN
 KOTA CIREBON
 KOTA SABANG
 KOTA JAMBI
 MAROS
 LAMPUNG BARAT
 MANGGARAI
 TUBAN
 LOMBOK TIMUR
 DOMPU
 KARANGASEM
 BANGKALAN
 KOTA BANDAR LAMPUNG
 PASER
 KOTA ADM. JAKARTA TIMUR
 CIAMIS
 KOTA SUKABUMI
 SIGI
 LUMAJANG
 KUDUS
 DEMAK
 MAGELANG
 BANTAENG
 DELI SERDANG
 BENGKULU SELATAN
 SEMARANG
 KOTA MALANG
 LANGKAT
 TASIKMALAYA
 NGAWI
 KOTA CILEGON
 KOTA ADM. JAKARTA BARAT
 SERUYAN
 KENDAL
 BATANG
 PROBOLINGGO
 KOTA TANGERANG
 SUKAMARA
 TEMANGGUNG
 TOJO UNA UNA
 KOTA MATARAM
 GROBOGAN
 BATANGHARI
 REMBANG
 PANGANDARAN
 ACEH TENGGARA
 SIAK
 KOTA MAKASSAR
 BANTUL
 BOLAANG MONGONDOW UTARA
 KOTA BANJARMASIN
 BANYUASIN
 KOTA SAMARINDA
 TOLI TOLI
 GOWA
 KOTA PADANG PANJANG
 KOTA PROBOLINGGO
 KOTA BIMA
 TRENGGALEK
 ACEH SELATAN
 SOLOK SELATAN
 OGAN ILIR
 MAJENE
 KOTA ADM. JAKARTA PUSAT
 KATINGAN
 INDRAGIRI HULU
 TOBA
 KOTA PEMATANGSIANTAR
 SUMENEP
 KOTA PAGAR ALAM
 MUSI RAWAS
 BUTON
 MESUJI
 SINJAI
  ROKAN HILIR
  PELALAWAN
 PIDIE JAYA
 BIREUEN
 BARRU
 ACEH TIMUR
 KOTA PEKANBARU
 MINAHASA
 HULU SUNGAI UTARA
 MEMPAWAH
 KOTA SORONG
 KOTA BANDA ACEH
 SITUBONDO
 MAMASA
 BERAU
 KEP. SIAU TAGULANDANG BIARO
 BENGKALIS
 SERAM BAGIAN BARAT
 BATU BARA
 GORONTALO
 NAGAN RAYA
 TAPANULI UTARA
 TANAH BUMBU
 PIDIE
 KLUNGKUNG
 PONOROGO
 SOLOK
 KOTA BUKITTINGGI
 LAHAT
 PARIGI MOUTONG
 TAKALAR
 PASAMAN
 MUSI BANYUASIN
 BOMBANA
 WAKATOBI
 WAJO
 PENUKAL ABAB LEMATANG ILIR
 BANGGAI
 PINRANG
 KOTA DUMAI
 PESISIR BARAT
 TABALONG
 DONGGALA
 BADUNG
 MALUKU TENGAH
 HUMBANG HASUNDUTAN
 KOTA BANJARBARU
 BUTON SELATAN
 NIAS SELATAN
 MELAWI
 SIJUNJUNG
 SIDENRENG RAPPANG
 TANA TORAJA
 POLEWALI MANDAR
 JAYAPURA
 JEMBRANA
 BULUKUMBA
 KOTA PAYAKUMBUH
 MUSI RAWAS UTARA
 KOTA PRABUMULIH
 KOTA PADANG SIDEMPUAN
 BENGKAYANG
 INDRAGIRI HILIR
 PADANG LAWAS
 BARITO TIMUR
 ACEH SINGKIL
 BANGLI
 TULUNGAGUNG
 KUANTAN SINGINGI
 BANYUWANGI
 TEBO
 LABUHANBATU SELATAN
 MANDAILING NATAL
 KEPULAUAN MERANTI
 SAMBAS
 TULANG BAWANG
 KEPAHIANG
 KOTA KEDIRI
 KOTA MADIUN
 KOTA BATU
 BANGKA TENGAH
 BANGGAI KEPULAUAN
 SAROLANGUN
 LAMPUNG UTARA
 KOTA DENPASAR
 KOTA PALU
 PULANG PISAU
 BANGKA BARAT
 KOTA TEGAL
  MERANGIN
 TAPANULI TENGAH
 SANGGAU
 KOTA TANJUNG PINANG
 KOTA MANADO
 LABUHANBATU
 MUARA ENIM
 TAPIN
 PENAJAM PASER UTARA
 TIMOR TENGAH UTARA
 KEPULAUAN SELAYAR
 LUWU
 EMPAT LAWANG
 MUNA
 NIAS BARAT
 LANDAK
 MALUKU TENGGARA
 BONE BOLANGO
 KARIMUN
 KOTA PALOPO
 MINAHASA SELATAN
 TANJUNG JABUNG BARAT
 KOTA TANJUNG BALAI
 MANGGARAI TIMUR
 MALINAU
 SOPPENG
 NIAS UTARA
 OGAN KOMERING ULU
 TORAJA UTARA
 LIMA PULUH KOTA
 BULELENG
 MALUKU BARAT DAYA
 HULU SUNGAI SELATAN
 RAJA AMPAT
 KOTAWARINGIN BARAT
 KEEROM
 KAYONG UTARA
 KOTA BONTANG
 BARITO UTARA
 KOTA PARIAMAN
 SUMBA TIMUR
 BINTAN
 GAYO LUES
  KERINCI
 NUNUKAN
 BARITO KUALA
 KOTA LHOKSEUMAWE
 BOLAANG MONGONDOW SELATAN
 KOTA AMBON
 KOTA TARAKAN
 BUTON UTARA
 AGAM
 BELITUNG TIMUR
 KOTA SINGKAWANG
 KOTA SIBOLGA
 KOTA GUNUNGSITOLI
 BANGKA SELATAN
 HALMAHERA TIMUR
 TAPANULI SELATAN
 KOLAKA
 MERAUKE
 KOTA BAU BAU
 MANOKWARI SELATAN
 KOTA MOJOKERTO
 PASANGKAYU
 HALMAHERA SELATAN
 KOTA TEBING TINGGI
 MINAHASA TENGGARA
 BONE
 TANGGAMUS
 SIMEULUE
 SUMBA BARAT DAYA
 ENREKANG
 ACEH BARAT DAYA
 REJANG LEBONG
 KONAWE SELATAN
 KOTA SOLOK
 KEPULAUAN YAPEN
 LABUHANBATU UTARA
 BOALEMO
 ROTE NDAO
 KOTA BANJAR
 ENDE
 KOTA BLITAR
 SELUMA
 MOROWALI
 YAHUKIMO
 KAB TIMOR TENGAH SELATAN
 TANAH DATAR
  ROKAN HULU
 PULAU TALIABU
 MAMUJU TENGAH
 KAUR
 KOTA BITUNG
 MINAHASA UTARA
 SAMOSIR
 KOTA LANGSA
 FLORES TIMUR
 KOTA SUBULUSSALAM
 BENGKULU TENGAH
 NIAS
 SINTANG
 BENER MERIAH
 KOTA BALIKPAPAN
 DHARMASRAYA
 KUTAI TIMUR
 KONAWE UTARA
 LUWU UTARA
 MUKO MUKO
 PANGKAJENE DAN KEPULAUAN
 BURU
 KAPUAS HULU
 KOTA MAGELANG
 KOTA JAYAPURA
 NATUNA
 BULUNGAN
 PASAMAN BARAT
 BANGKA
 MAPPI
 HALMAHERA BARAT
 TELUK BINTUNI
 ASMAT
 SERAM BAGIAN TIMUR
 BUTON TENGAH
 NGADA
 SUMBAWA
 KOTABARU
 KOLAKA UTARA
 ACEH BARAT
 KOTA SUNGAI PENUH
 LUWU TIMUR
 KOTA SAWAHLUNTO
 POSO
 ACEH JAYA
 BELITUNG
 KAPUAS
 KOTA TOMOHON
 KOTA TIDORE KEPULAUAN
 KOLAKA TIMUR
 BANGGAI LAUT
 NABIRE
 MANGGARAI BARAT
 POHUWATO
 KOTA GORONTALO
 SARMI
 KOTAWARINGIN TIMUR
 LEBONG
 BOLAANG MONGONDOW
 SEKADAU
 SUMBAWA BARAT
 BUNGO
 GORONTALO UTARA
 KEPULAUAN ARU
 MURUNG RAYA
 KOTA TUAL
 KAIMANA
 SORONG
 KOTA KOTAMOBAGU
 BELU
 ALOR
 WAROPEN
 KUTAI BARAT
 BURU SELATAN
 TELUK WONDAMA
 SUMBA BARAT
 KEPULAUAN SULA
 KONAWE KEPULAUAN
 BIAK NUMFOR
 KEPULAUAN TALAUD
 LEMBATA
 KEPULAUAN ANAMBAS
 TANA TIDUNG
 BUOL
 BOVEN DIGOEL
 FAK FAK
 LAMANDAU
 KEPULAUAN TANIMBAR
 ADM. KEP. SERIBU
 SORONG SELATAN
 SABU RAIJUA
 SUPIORI
 MOROWALI UTARA
 PAKPAK BHARAT
 BOLAANG MONGONDOW TIMUR
 SUMBA TENGAH
 PULAU MOROTAI
 GUNUNG MAS
 HALMAHERA TENGAH
 DEIYAI

# Jumlah Kelurahan/Desa SPPG yang punya sppg

In [61]:
# Menghitung jumlah desa unik yang punya SPPG
jumlah_desa_unique = df['Kelurahan/Desa SPPG'].nunique()

# Mengambil daftar nama DESA unik (bukan Kab./Kota)
list_desa_kelurahan = df['Kelurahan/Desa SPPG'].unique()

print(f"Jumlah desa/kelurahan yang punya SPPG: {jumlah_desa_unique}")
print("Daftar desa/kelurahan yang punya SPPG:")

for des in list_desa_kelurahan:
    print(f"- {des}")

Jumlah desa/kelurahan yang punya SPPG: 14069
Daftar desa/kelurahan yang punya SPPG:
-  ADIWARNO
-  SUNGAI PINANG
-  TEMBESI
-  TUNGGALROSO
-  SINDANGRAJA
-  MAULAFA
-  KARANG SARI
-  PAMURUYAN
-  TONDASI
-  KADIPIRO
-  TAPUANG
-  PANDOWAN
-  SUNGAI PAGAR
-  KLATEN
-  SUMBERAGUNG
-  MUKTISARI
-  SUNGAI PANAS
-  BEURINGEN
-  PEPELEGI
-  DRIYOREJO
-  DOPLANG
-  PEKUNCEN
-  TAMPANG
-  CABI
-  TLAMBAH
-  NAMBAH DADI
-  KERTICALA
-  TAJURHALANG
-  KETAPANG TIMUR
-  ROROTAN
-  PURWOSARI
-  JAYANTI
-  KORUMBA
-  JATIKUWUNG
-  SEPANG
-  SUKOMULYO
-  NGLEGOK
-  PANDAN SARI
-  CIRIUNG
-  CEBOLEK KIDUL
-  NEGERI SAKTI
-  PAGERKUKUH
-  KARANGPUCUNG
-  NANGKAKONENG
-  MBAY I
-  SUMBEREJO
-  KARANGKATES
-  BOJONGKOKOSAN
-  KOTO BERAPAK
-  SIANTAN HILIR
-  KIANGROKE
-  PANDEAN LAMPER
-  MUARA JEKAK
-  KOTA KULON
-  MULYOHARJO
-  SIRNOBOYO
-  MEKARJAYA
-  BUJAK
-  BALEHARJO
-  JAKASAMPURNA
-  TAMAN ASRI
-  KRANJINGAN
-  PACIRAN
-  WANGUNSARI
-  PEMETUNG BESUKI
-  GELE PULO
-  SINDANGWANGI
-  MOJORUNTUT
-  GANDASULI
-  CIAPUS
-  TAKARI
-  AMBAN
-  DURIAN RAMPAK
-  CIRIMEKAR
-  TAWANGHARJO
-  SINGAPADU
-  SAMBONGDUKUH
-  CIBEBER
-  CIJUNTI
-  SONDOANG
-  BIRU
-  DONOWANGUN
-  SURUSUNDA
-  KINEPPEN
-  MENTENG
-  ARJAWINANGUN
-  CEBONGAN
-  MURTIREJO
-  NGABUL
-  SUKADANA ILIR
-  SIALANG BUAH
-  MUARO PIJOAN
-  WONOSEKAR
-  PASAWAHAN
-  MARIPARI
-  KALIDONI
-  CIPEUNDEUY
-  JASINGA
-  SARADAN
-  TUNGGALPAGER
-  DONOMULYO
-  BANTARGEBANG
-  SUMBER WARU
-  KADEMANGAN
-  KRAMATWATU
-  MUKTIHARJO
-  CIPULIR
-  KUBU DALAM PARAK KARAKAH
-  JATIREJOYOSO
-  PARAKANTUGU
-  TELADAN TIMUR
-  SISWODIPURAN
-  KANDANG MAS
-  CILEUNGSI KIDUL
-  KALIORI
-  JOMBATAN
-  OEPURA
-  COKROWATI
-  WARAKAS
-  RAJADANU
-  SOKOBANAH DAYA
-  SANGA-SANGA DALAM
-  KECILA
-  SUKOMALO
-  CILEDUG KULON
-  BAHAGIA
-  KRAJAN
-  KARET
-  KARTINI
-  PUNGGUR BESAR
-  MAMPANG
-  AIK MUAL
-  KALI BAROS
-  GEMBONGDADI
-  TEMU
-  PALAJAU
-  JATI
-  DAIK
-  WATULIWUNG
-  PANDA
-  KALIBUNDER
-  MONTOK
-  NOTOPRAJAN
-  PURBAYAN
-  JATIWARINGIN
-  LIMA-BELAS ILIR
-  CERIH
-  TAPOS
-  SUKOREJO
-  MALAI V SUKU
-  BUMI HARAPAN
-  CIBUYUR
-  PONCOGATI
-  PONCOWARNO
-  BEGAJAH
-  SAMA GUNA
-  CISALADA
-  HETUMA
-  JATI MULYO
-  JELOK
-  HEGARMANAH
-  PASIRDOTON
-  TOGAWABESI
-  GUNUNG SARI
-  KERTA BUANA
-  AMBAT
-  NUSAMANGIR
-  TANJUNG NERACA
-  NIBUNG PUTIH
-  KEBON PISANG
-  GIRI KENCANA
-  TEMBOK DUKUH
-  BOJONG RAWALUMBU
-  PARASREJO
-  CIKULUR
-  SAREN
-  KALIGONO
-  SUKAMULYA
-  KEMIRI
-  KAMORO JAYA
-  TAABA
-  AROMBU
-  KEDUNGREJO
-  SONGGOM
-  NAGARASARI
-  SINAR MULYO
-  SINYEU
-  CIKAWUNG
-  PARBULUAN III
-  ABIAN TUWUNG
-  TURI
-  NAGARAWANGI
-  RAGUNAN
-  PASIRTALAGA
-  KEBONAGUNG
-  SEI RENGGAS
-  HUTALOMBANG
-  CIDAHU
-  TEMPINO
-  MAJAPURA
-  CIKARAGEMAN
-  TUGUREJO
-  SINDANGJAWA
-  HILIR SEPER
-  GERGUNUNG
-  CIREUNDEU
-  WARUNGDOWO
-  MEKAR BAKTI
-  GERUNG UTARA
-  GEGESIK KIDUL
-  WAWAI GARDU
-  SRIWIJAYA
-  KERTAMAYA
-  KEDAWUNG
-  HARJOBINANGUN
-  GUDANGKAHURIPAN
-  WONOSARI
-  DRAJAT
-  KUTA BARAT
-  KARANGJOHO
-  BAKBAKAN
-  HANDIL JAYA
-  LEBAKWANGI
-  MA'RUMPA
-  CIJORO LEBAK
-  PAJAR BULAN
-  WRINGINHARJO
-  NENU
-  GEDONGOMBO
-  PAOKMOTONG
-  KANDAI II
-  RAJA TIMUR
-  SUBAGAN
-  PAGERALANG
-  TAMANSARI
-  PUTAT NUTUG
-  TEGAL GUNDIL
-  GROGOL
-  CAMPOR
-  LABUHAN DALAM
-  JONE
-  PENGGILINGAN
-  JATIKRAMAT
-  PERINA
-  MALEBER
-  WARUDOYONG
-  TANJUNG KUKUH
-  WALATANA
-  KRAI
-  SINGOCANDI
-  KEDAUNG
-  NARAWITA
-  WATESTANJUNG
-  SITUMEKAR
-  KALIANYAR
-  SUNTER JAYA
-  KARANGSARI
-  PUCUNG
-  BAGU
-  MIJEN
-  CILAME
-  PASIR IMPUN
-  PAGAR DEWA
-  KARANGANYAR
-  SUKABUMI
-  BONTO JAI
-  KELAMBIR
-  KEBONDALEM
-  BANTUR
-  MAJAKERTA
-  KEBON MANGGIS
-  CIGAGADE
-  REMPUNG
-  PASAR BARU
-  PASIR PUTIH
-  JATINEGARA KAUM
-  DANGDEUR
-  BANDARJO
-  KASIN
-  BENTENG
-  ARA CONDONG
-  GIRIJAYA
-  GADOG
-  PANIMBANGJAYA
-  KLITIK
-  KEMURANG KULON
-  MASANGANKULON
-  JOMBANG WETAN
-  SUKABUMI UTARA
-  BATUBULAN
-  WAILITI
-  SUKAWANGI
-  RUNGAU RAYA
-  DARAT
-  CURUGSEWU
-  JAKAMULYA
-  KELAPA DUA WETAN
-  SUKOLILO
-  CURUG
-  GEDONG AIR
-  PANYINDANGAN
-  CIPAGERAN
-  MARGODADI
-  SUNGAI LANGKAI
-  SIDOREJO
-  CIMANUK
-  BANYUANYAR TENGAH
-  SEMARANG
-  TIGA ILIR
-  PETIR
-  KASANG
-  GEDONG
-  BANGBAYANG
-  TUMPOK MESJID
-  CIBADAK
-  NATAI SEDAWAK
-  SAWAHAN
-  MERDEN
-  PAGOJENGAN
-  KUTANAGARA
-  KANDANGAN
-  BATU MULYA
-  UENTANAGA ATAS
-  SUMBERHARJO
-  AMPENAN SELATAN
-  LALANG
-  PONDOK RANJI
-  PENGKOL
-  PASAR MUARA TEMBESI
-  KEBLUKAN
-  PASIRGEULIS
-  KARANGWUNI
-  PASUCEN
-  JEPANG
-  PEKUWON
-  PULONAS
-  MUARE
-  JOGLO
-  BARUGA
-  SIMPANG BELUTU
-  BITOWA
-  KALIWADAS
-  TRIHARJO
-  MATUA
-  CIKATAPIS
-  BOROKO
-  SITU ILIR
-  KLAMPISAN
-  CIPARI
-  KARYA TANI
-  TANJUNG PAGAR
-  MARIANA ILIR
-  MANGGIS
-  MANGUNSARI
-  JADIMULYA
-  SAWOJAJAR
-  MEKARSARI
-  KAMAL
-  BANJARAN
-  KESAMBI
-  KEBONMANIS
-  SEMPAJA BARAT
-  MANGGISAN
-  KEJIWAN
-  PLAOSAN
-  BARU
-  DRUJU
-  BONTORAMBA
-  PARAK LAWEH PULAU AIA NAN XX
-  BOGAK BESAR
-  BUKIT SURUNGAN
-  JENGGIK
-  CURUGKEMBAR
-  SUKABANGUN
-  PULOSARI
-  KRANDEGAN
-  SANGGREMAN
-  JATIRADEN
-  ILIR
-  PUCANGTELU
-  SANGIANG
-  NGUMPUL
-  LIMAU MANIS
-  KANIGARAN
-  MANDE
-  WAIOTI
-  AMPLAS
-  PRANGGANG
-  KARANGSOKO
-  KAHURIPAN
-  PATEMON
-  TANJUNG ANOM
-  KALIBARU
-  SIMALINYANG
-  LHOK AMAN
-  GUNUNGELEH
-  LUBUK GADANG
-  DAREN
-  SUNGAI PINANG II
-  CIKALONG
-  TULUSREJO
-  TAMAN ROYA
-  SARDONOHARJO
-  TAN SARIL
-  NAGRAK UTARA
-  SALUTAMBUNG
-  KEMAYORAN
-  PAGATAN HILIR
-  PUNTI ANAI
-  CILOLOHAN
-  DORA TANGGA
-  HUTANAMORA
-  TAMBAKAGUNG
-  KEDUNGUPIT
-  BUGEL
-  TIMBANG GALUNG
-  BANJARMENDALAN
-  CIMARIAS
-  KARANGMULYA
-  TAKOMA
-  PANDEMAN
-  BANGUN REJO
-  SALAMNUNGGAL
-  LEMAHPUTRO
-  BUKO
-  CIRUMPAK
-  ANYAR
-  SURANENGGALA
-  WAGARI
-  TALANG JERINJING
-  CEMENGBAKALAN
-  BANYU BUNIH
-  PERIGI
-  BENCONGAN
-  PASANGGRAHAN
-  CILEUNYI WETAN
-  MUKTI KARYA
-  TONGKE-TONGKE
-  BAGAN BATU KOTA
-  BLUBUK
-  LANGGAM
-  SAGOE
-  UTEUN SIKUMBONG
-  COPPO
-  RAJABASA
-  TRIKOYO
-  PAYA BILI SA
-  SENDANG AYU
-  GUNUNG SAHARI UTARA
-  PASIR NUNGGUL
-  JIKEN
-  TANGKERANG BARAT
-  KARANGASEM
-  TAWANGREJO
-  ANTAPANI KIDUL
-  GABUGAN
-  PAMOYANAN
-  GEBANG ILIR
-  SUKAMISKIN
-  TERATAK
-  MERBAU MATARAM
-  TEGALMANGGUNG
-  PANGAUBAN
-  BOJONGGEDE
-  KARANGAGUNG
-  CENGKARENG BARAT
-  MLALE
-  PURWOKERTO
-  DUKU
-  SENDANGREJO
-  MUARA KELINGI
-  KARASAK
-  LUBUK PAKAM PEKAN
-  SUKARASA
-  RERER
-  PALIMBANGAN
-  DARU
-  GENTENG
-  WONOLELO
-  WUNUT
-  MELIRANG
-  SUNGAI PINYUH
-  SUKARESMI
-  BENDOAGUNG
-  CANDINGASINAN
-  SIMPANG III SIPIN
-  CISEREH
-  MALAINGKEDI
-  LAMLAGANG
-  NYALINDUNG
-  SINAGAR
-  MANYETI
-  TANJUNG RAJA
-  TENGAH
-  PONDOK CABE UDIK
-  LAWIR
-  TALKANDANG
-  CIGENTUR
-  MACCINI BAJI
-  MANGUNREJO
-  PULAU BIRANDANG
-  BATANG URU
-  WALANGSARI
-  GERUNG SELATAN
-  MARGALAKSANA
-  SEI PUTIH TIMUR II
-  GAYAM
-  CIPEDES
-  REK KERREK
-  KRAMAT
-  TERUKIS RAHAYU
-  MINI
-  JATISARI
-  SEJANGAT
-  MEDOKAN AYU
-  LARANGAN
-  LUHU
-  PASIR GUNUNG SELATAN
-  WARINGINJAYA
-  TOBEKGODANG
-  LOPANG
-  CIJEDIL
-  KUALA INDAH
-  BALAI GADANG
-  SULAIMAN
-  CIBOLANG KALER
-  PASIRHUNI
-  SIDOWAYAH
-  DARMA SAKTI
-  GUNUNG MULYA
-  TAMBAKSARI
-  BANYUPUTIH LOR
-  BANGSRI
-  TRIDHARMA
-  CIAWI
-  BAGAN SINEMBAH
-  SRUWENG
-  SUKAMANAH
-  MARICAYA BARU
-  KETOYAN
-  KETAPANG
-  GRATITUNON
-  PANGGARANGAN
-  WELAHAN
-  PATAM LESTARI
-  BRAJA MULYA
-  GEJUGJATI
-  BOJONG PONDOK TERONG
-  KOTA GALUH
-  GRUDO
-  KUTOSARI
-  SENDANGAN
-  SIRNAJAYA
-  KEMBANGKUNING
-  JAJAR
-  BLANG SEUMOT
-  CIMANGGU
-  SIPAHUTAR I
-  KEPATIHAN
-  SERDANG WETAN
-  PASINDANGAN
-  KARANGREJO
-  BENUA RAJA
-  SUNGAICUKA
-  JATIMEKAR
-  BLANG TEUNGOH
-  SRIWEDARI
-  JATINGALEH
-  SUKAHATI
-  WANDANPURO
-  SELAT
-  PULOKERTO
-  ARJASARI
-  LEMBUNG PASESER
-  GUNTING
-  BANTARSARI
-  KALONGAN
-  SUKAJAYA
-  PALABUAN
-  KARANGLO LOR
-  MUARO PANEH
-  WANASARI
-  SOTEA
-  GUNUNGGURUH
-  PIDADA
-  LINGKIS
-  KEDUNGROJO
-  BATURITI
-  SUKOHARJO III
-  PIJIHARJO
-  KUBU GULAI BANCAH
-  BANDAR JAYA
-  ARENJAYA
-  BUKITLAMA
-  DONGGULU
-  JATIJAJAR
-  TRIMULYO
-  SIMPANG KELAPING
-  SUMURAGUNG
-  PALLEKO
-  CERME
-  BHINOR
-  PACAR KELING
-  LEKSANA
-  BLIGO
-  KEPUH
-  SENGKOL
-  SAKRA
-  LADANG PANJANG
-  BELOR
-  HARGOMULYO
-  SUNGAI LILIN JAYA
-  BABAKAN
-  CISEWU
-  KUNTI
-  RANGKAPAN JAYA BARU
-  TRATEMULYO
-  BLANG PEURIA
-  PARIA
-  SIMPANGBARU
-  PULEDAGEL
-  PONGO
-  LEUWILIANG
-  FIRDAUS
-  LAIKANG
-  TANJUNGMEKAR
-  CAMPALAGI
-  MAGETAN
-  CIKANDE PERMAI
-  MUARA SUNGAI
-  CIKADU
-  TOILI
-  TELAGA TUJUH
-  KARANGJAYA
-  TANJUNGSARI
-  GERSEMPAL
-  LEMPANGANG
-  TENGGELES
-  TIMURAN
-  WONOREJO
-  KALISARI
-  KECIPIR
-  PADAKKALAWA
-  PURWODADI
-  HELVETIA
-  GANUNG KIDUL
-  NGA MATANG UBI
-  SINGAMERTA
-  SUKAMAJU
-  MARGAJAYA
-  TELUK BINJAI
-  BIRA BARAT
-  DAMPIT
-  GEDUNG JOHOR
-  MUSUK
-  PASAR KRUI
-  TANJUNGKERTA
-  WIRANG
-  KARUNRUNG
-  KAUMAN
-  LONG
-  PELUTAN
-  CIMUNING
-  GIRIREJO
-  BANGKO PERMATA
-  TAMAN BALOI
-  POPONGAN
-  CIKEDOKAN
-  BERAN
-  CIPOCOK JAYA
-  JIMBARAN
-  OMA
-  BONTO TIRO
-  TANJUNG HARAPAN
-  TINJOMOYO
-  KERTAMANDALA
-  LABUAN
-  KALIERANG
-  SERANG
-  CINANGSI
-  PAKKAT HAUAGONG
-  PUGUNG RAHARJO
-  PALAM
-  SUKARAJA
-  TONGALI
-  SUNGAI BILU
-  PLAWAD
-  TANAH MERAH
-  KARANGKEMBANG
-  KARYAMUKTI
-  KALIPANCUR
-  KEDONGDONG
-  BATU PANJANG
-  KOBER
-  CIPAREUAN
-  TUMPUK
-  TIRTO
-  TANABANGKA
-  SAMUTI MAKMUR
-  BAWONAHONO
-  BULU
-  SELOMARTANI
-  PANCORAN MAS
-  CIBURIAL
-  KARANGPAKIS
-  MULYOREJO
-  PECALUKAN
-  PAAL
-  LIMO KOTO
-  CIKARANGKOTA
-  JALAN GEDANG
-  SUKASETIA
-  KEBUTUH
-  SETIADARMA
-  SIDOHARJO
-  TEGALGEDE
-  CISAYONG
-  CIBENING
-  PAL SEMBILAN
-  KORPRI JAYA
-  TENJONAGARA
-  MALINGPING UTARA
-  POTROYUDAN
-  SAMUDA
-  SIMPANGAN
-  BATU LAPPA
-  LAJU
-  JOGOTRUNAN
-  NITA
-  MULYA HARJA
-  SADU
-  MEKAR SARI
-  RARANG
-  TAMBUNAN
-  SIALANG
-  GLAGAHWERO
-  SUKAHAJI
-  KALIJATI TIMUR
-  CAKUNG TIMUR
-  MALANU
-  BANGUN SARI
-  CIKOLELET
-  PARIT BUGIS
-  UMALOR
-  PANARAGAN
-  PETAMPANUA
-  GUNAMEKAR
-  SUKADAMAI
-  CISEENG
-  RANGKASBITUNG BARAT
-  TABRI
-  BANJAR TENGAH
-  BIREM
-  PATIANROWO
-  BATUKAROPA
-  DAYA MAKMUR
-  TITIWANGI
-  BATU SELICIN
-  LOJI
-  SEBANI
-  LEUWIGAJAH
-  WANASIGRA
-  TIAKAR
-  ALAS RAJAH
-  PODOSUGIH
-  JAYAMUKTI
-  MUARA BATANG EMPU
-  JUNWANGI
-  GIRIKERTO
-  LUNDONG
-  KELAKIK
-  GORUA SELATAN
-  TANJUNG PALAS
-  BULAK BANTENG
-  PEKIRINGAN
-  MUNTANG TAPUS
-  JORING NATOBANG
-  KEDIRI
-  RAWA BUAYA
-  BAMBU APUS
-  TEMBUNG
-  DELI TUA TIMUR
-  KLUMPANG KAMPUNG
-  PAKINTELAN
-  SELUAS
-  JATILAKSANA
-  SEI REJO
-  SUMBERSARI
-  SUMUR PECUNG
-  TAUBONTO
-  BONTO MANAI
-  SUKABUNGAH
-  SUKATANI
-  NGAMPIN
-  SANDINGROWO
-  TAMANAGUNG
-  PANGKABINANGA
-  KARANGMANGU
-  NGAMPEL
-  PONGGOK
-  RAPAK DALAM
-  KADU AGUNG
-  FATULULI
-  TASIK MADU
-  BIRIT
-  MUARA BELITI BARU
-  CIAMIS
-  CAMPAKA
-  CIBENTANG
-  BANDAR TONGAH
-  PENDOSAWALAN
-  SUKALAKSANA
-  BAGAN JAYA
-  CIPINANG MUARA
-  SAMPANGAGUNG
-  MINAS TIMUR
-  SIDOARUM
-  SEMPAJAYA
-  LESES
-  HASAHATAN JULU
-  SUMBERJAYA
-  SARIPAN
-  TANJUNG GUSTA
-  GLADAK ANYAR
-  PAGONGAN
-  PASAR PANAS/TANIRAN
-  TENGARAN
-  PAPAR
-  JATAKE
-  TALANGKEMBAR
-  CINERE
-  WANDOKA SELATAN
-  SAPARUA
-  MENILO
-  AKCAYA
-  JENARSARI
-  TIROANG
-  PADASUKA
-  SUKAMEKAR
-  TALAGA
-  CIREUNGHAS
-  PETAMBAKAN
-  RAWA KIDANG
-  MERUYA UTARA
-  SUMBER SALAM
-  TALANG BABUNGO
-  AIR JAMBAN
-  DASAN GERES
-  KRIKILAN
-  TROSO
-  SINDANGSARI
-  TANJUNG
-  GELAM SEI SERIMAH
-  DADAPAN
-  SANTAN TENGAH
-  SUMBER REJO
-  GLUMPANG PAYONG
-  SEMPER BARAT
-  PAKIS
-  KAJEN
-  GARI
-  CEPER
-  CIPATUJAH
-  PADARINGAN
-  BUKIT HARAPAN
-  MANGUNAN
-  NAMO MBELIN
-  JATIENDAH
-  KAWAN
-  BUKET HAGU
-  PAKEL
-  TITIAN MODANG KOPAH
-  BUNGO PASANG
-  TEGAL REJO
-  CIKAWAO
-  SUKA BARU
-  KERTAJAYA
-  PANDESARI
-  JURANGMANGU TIMUR
-  PETERONGAN
-  RAHAYU
-  TIRTOMOYO
-  SARIREJO
-  PRIGI
-  MUARA TEBO
-  PERK. TOLAN
-  SELINDUNG
-  TERTEK
-  CILAMAYA
-  SUGIHWARAS
-  MAKU
-  PASAR KOTANOPAN
-  CUKIR
-  LOYOK
-  SUELA
-  JATI BARU
-  SUNGAI TOHOR BARAT
-  BAGELEN
-  BULUTENGGER
-  KEDALEMAN
-  PETUNG
-  GERNING
-  BABAKANCIKAO
-  SOA
-  BETUNG
-  KARANGRAHARJA
-  PATARUMAN
-  BIYONGA
-  MULIA
-  DALAM KAUM
-  SIDAKATON
-  TERATE
-  SAMBIROTO
-  BARATAN
-  CANGKRING
-  SAWAH
-  PARUGA
-  KUTABANJARNEGARA
-  MANOKWARI BARAT
-  KADUPANDAK
-  TAMBA'AN
-  BUKIT INDAH
-  DRAMAGA
-  NAGREG KENDAN
-  TENJOLAYA
-  PERESAK
-  KALANGSURYA
-  SUKAMENAK
-  CIHIDEUNGUDIK
-  SINDANGPALAY
-  TAMBANG
-  SIDOMULYO
-  BATANG HARI
-  SEGALAMIDER
-  CIKIWUL
-  TANGKILING
-  DURIAN DEPUN
-  SOGAAN
-  BABAGAN
-  DABUK MAKMUR
-  KONDANGJAYA
-  BAROS
-  TANJUNGWANGI
-  JEPARA
-  SINDANGKERTA
-  SEMAMPIR
-  BUKET PANYANG DUA
-  NGEGONG
-  JATIREJO
-  SETIA ASIH
-  JAMPANGTENGAH
-  MOJOREJO
-  JELUTUNG
-  SAMBIUT
-  KAPUAN
-  PALLANTIKANG
-  SALAMAN
-  TEUPIN KEUBEU
-  MOJOLANGU
-  PASIRANGIN
-  NGUNUT
-  SUNGAI ULIN
-  BALUNGLOR
-  KARANGMEKAR
-  CURUGRENDENG
-  CIBITUNG
-  PELAS
-  WATUGEDE
-  MONTONGSEKAR
-  PULAU PANDAN
-  RAGATUNJUNG
-  BABELANKOTA
-  BANDAR LOR
-  RAMBATAN WETAN
-  SEMULI JAYA
-  POGALAN
-  TRIRENGGO
-  CITEREP
-  SANUR
-  LEBAKMUNCANG
-  TLOKOH
-  SUMBERARUM
-  DUKUH
-  TANAMODINDI
-  TELUKJAYA
-  NARU
-  KEBON BARU
-  BUMIHARJO
-  WUNGUREJO
-  SUKOMANUNGGAL
-  PETUK LITI
-  KAPALO KOTO AMPANGAN
-  SUNGAI BARU
-  LEBAK WANGI
-  GEDONG MENENG
-  KALIJAGA
-  JAYABAKTI
-  RAMA DEWA
-  BUMI AGUNG
-  GAMPONG TEUNGOH
-  GIRIKULON
-  UMAKATAHAN
-  TAMAN
-  PANGGUNG
-  PAGU
-  BANYUDONO
-  DUSUN BANGKO
-  MARGAGIRI
-  TUMBA JAE
-  PENGASIH
-  TANAP
-  PERWIRA
-  BRAJAN
-  NAGASARI
-  CIMAHPAR
-  JAMBANGAN
-  PETUKANGAN UTARA
-  KALIWUNGU
-  GUNUNGMANIK
-  SUMBERGANDU
-  GARUNG LOR
-  MARENGAN DAYA
-  PANGKALAN
-  DAWUNG
-  GONDANGLEGI
-  PABUARAN LOR
-  ANGGARAKSA
-  TAWANGSARI
-  KEDUNGOMBO
-  TANJUNG AYUN SAKTI
-  SINDANGANGIN
-  MANJAHLEGA
-  PASIRBUNGUR
-  CISARUA
-  SIRNASARI
-  SEI APUNG
-  TEMPURSARI
-  SUNGAI BAKAU KECIL
-  BINJAI
-  BEBIDAS
-  BANE
-  TAMANHARJO
-  BANANGKAH
-  KEDUNG HALANG
-  SINGKIL SATU
-  TEBING LINGGAHARA
-  CIPINANG CEMPEDAK
-  SIMBORO
-  PONDOK BENDA
-  MANDI AUR
-  BANJAR AGUNG
-  CIKANCUNG
-  BALI SADHAR SELATAN
-  PASAR I MUARA ENIM
-  CIPERNA
-  BINTARA
-  TANJUNG BATU
-  PEMATANG KARANGAN HULU
-  KUALA DUA
-  PAPANGGO
-  DERWATI
-  TAKALAR
-  CIPTA MUDA
-  SUMBER HARTA
-  KENTENG
-  BLANG ME TIMU
-  BLU URAN
-  CIRANJANG
-  SITUDAM
-  KAMPUNG BULANG
-  TIMBULUN
-  PURUS
-  BINONG
-  PEPE
-  SOREK I
-  KEDUNGWUNI BARAT
-  TANJUNGAN
-  TUGUJAYA
-  LEMBO
-  JAYAGIRI
-  PANCAWATI
-  SASI
-  KAMPUNG KELAWI
-  MANDALASARI
-  GUNUNGBUNDER II
-  NYIUR INDAH
-  SUKARAMAI I
-  KETOMPEN
-  CILILIN
-  RAWASARI
-  PURWOHARJO
-  GANDUL
-  BEBANGA
-  PUCANG
-  BEBEKAN
-  KRANJI
-  ANGSAU
-  JATINEGARA
-  SETIAREJO
-  TERUSAN LAMA
-  ARGASUNYA
-  CIMENYAN
-  SUMUR
-  SRI MULYO
-  WIRO
-  MUNCANG
-  KEMBANGARUM
-  NGASINAN
-  BANGUNHARJO
-  CIWARINGIN
-  KAYURINGINJAYA
-  JORONGAN
-  WAKOBALU AGUNG
-  CIJAYA
-  WONGSOREJO
-  PALEDANG
-  LUBUK PAKAM I,II
-  SEI KAMAH II
-  TANJUNG PADANG
-  LAMBANGSARI
-  PAKUNIRAN
-  NGESTIHARJO
-  SEI ALIM HASAK
-  PASIRAN
-  NEGERI KATON
-  BULUH
-  CIPUTAT
-  SARANG HALANG
-  WARUNGBAMBU
-  SEI MENCIRIM
-  SUKAJADI
-  BINANGUN
-  SUNGAI DERAS
-  MANGINDARA
-  KELAPA LIMA
-  SUKA ASIH
-  BIROBULI SELATAN
-  PAGENJAHAN
-  SUNGAI KAKAP
-  RANCABUNGUR
-  PATONGLOAN
-  WAUNG
-  KANDIS
-  TEGALMAJA
-  SEPANJANGJAYA
-  ADU MANIS
-  RAYA HULUAN
-  KETAREN
-  NEGERI BARU
-  KARYA BAKTI
-  BABADSARI
-  KOPANG REMBIGA
-  RAWAKALONG
-  CIKUDA
-  TANJUNG RANCING
-  KAMPUNG REMPAK
-  DAUH PEKEN
-  CIPAWON
-  KEDUNGWARU
-  BATUJAJAR BARAT
-  BERINGIN RAYA
-  CINANGKA
-  SUMOGAWE
-  KERTABUMI
-  PISANGAN
-  KABONENA
-  KECAPI
-  KARANGPANDAN
-  TAMAN CARI
-  PISANG BARU
-  BERNGAM
-  CIKIJING
-  FADORO
-  KINTAP
-  CIRANCA
-  KEMALANG
-  RANTAU PANJANG
-  HILIR KANTOR
-  WEARLILIR
-  PUTATLOR
-  PASARBATANG
-  LENGKONG WETAN
-  RAWA TERATE
-  MEKARASIH
-  CICALENGKA
-  PERDAMAIAN
-  MUSTIKASARI
-  PARU KEUDE
-  PRINGGA JURANG
-  EHO
-  JATIASIH
-  BOJONGLOA
-  MERGAYU
-  MACORAWALIE
-  BEUSA SEBERANG
-  KOTA LAMA
-  BLOTONGAN
-  ASEM KANDANG
-  PURBASARI
-  TALUDAA
-  NGRAYUNG
-  SIGANDO
-  LUWOO
-  MEUNASAH BLANG
-  GAYAMSARI
-  WANGUK
-  PADARNI
-  PANTOLOAN
-  SRATUREJO
-  LEBAK BULUS
-  SUNGAI PASIR
-  KREBET
-  DEKETKULON
-  SUNGAI KEDUKAN
-  TELING ATAS
-  AMBARAWA
-  RASAU JAYA SATU
-  CANDI MAS
-  MENGGORO
-  HADIWARNO
-  MARGAWANGI
-  CURUGBARANG
-  NARUMONDA V
-  BATUNUNGGAL
-  PANJEREJO
-  BALANDAI
-  RAWANG GUNUNG MALELO SURANTIH
-  GUNUNGSINDUR
-  SUCEN
-  SUKARATU
-  HARAPANJAYA
-  BALAI PANJANG
-  SUSUKAN
-  BALAI PINANG
-  ASAM KUMBANG
-  PETATAL
-  SOKOMORO
-  KARANG TENGAH
-  LAMPREH LAMTEUNGOH
-  KEMADANG
-  PALASARI
-  CIKIDANG
-  WANAJAYA
-  KINAWERUAN
-  PEKAJANGAN
-  KEDABU RAPAT
-  KARANG DALO
-  PANDANGAN KULON
-  MIMBAAN
-  CIJOHO
-  TANJUNGANOM
-  CATURTUNGGAL
-  BONTOA
-  CIGINGGANG
-  JETIS
-  BANJARSARI
-  SIDOMUKTI
-  TUNGKAL HARAPAN
-  MANDALAWANGI
-  SELATPANJANG TIMUR
-  SUKAHURIP
-  TONJONG
-  CIROYOM
-  WRINGINPUTIH
-  WINANGUN SATU
-  RANCATUNGKU
-  CIKUYA
-  SUKARESIK
-  RAGAJAYA
-  MIRU
-  PAHANG
-  TANI AMAN
-  PULISEN
-  SERASAN JAYA
-  PANYAKALAN
-  CIPANGERAN
-  AMANSARI
-  RAJABASA LAMA I
-  JATIROTO
-  SIRNAGALIH
-  SERPONG
-  NGEMPLAK LOR
-  BUKIT TUNGGAL
-  TAPAK SIRING
-  RAKAM
-  ALASWANGI
-  BUNGURSARI
-  BAGAN BATU
-  UJUNGJAYA
-  MLEKANG
-  SUKANAGARA
-  TANJUNG PINANG KOTA
-  KALIABANG TENGAH
-  SESO
-  KARANGMALANG
-  SUAK TEMENGGUNG
-  CIBUNTU
-  BANTAS
-  ANDURING
-  SOREANG
-  MEKARJADI
-  KEUDE DUA
-  TRITIS
-  KARYAMULYA
-  SATAR PEOT
-  GEDAWUNG
-  SUKAPURA
-  BROTONEGARAN
-  KUTOANYAR
-  BERBEK
-  KRETEK
-  MALIMPUNG
-  MUNJULJAYA
-  SIWULUH
-  KEBUN TEBENG
-  MALONAS
-  KUALA LAPANG
-  ENTIKONG
-  TOBULUNG
-  DUKUHWARU
-  MUARO
-  LEBO
-  BALUNGKULON
-  BANTUL
-  MALAKA
-  BENDA BARU
-  COT GAPU
-  SEUNEUBOK PEUSANGAN
-  BUGIS
-  GAMBUT
-  SIMPANG EMPAT
-  JOMBOK
-  GEMBOR UDIK
-  CREWEK
-  JAYAPURA
-  SUMBER
-  SUKADANA
-  ARJOWINANGUN
-  TEGALDOWO
-  KEDUNGJENAR
-  SUNGAI KELEDANG
-  LARINGGI
-  KEMBUAN
-  BAGO
-  GUNUNGSARI
-  SENTANI KOTA
-  BAHO
-  CINYAWANG
-  CIKASUNGKA
-  JUNREJO
-  SLAWI KULON
-  MEUNASAH LEUBOK
-  SEKAR JAYA
-  PEKKABATA
-  RINDING BATU
-  CIPAKU
-  ULEE GLEE
-  SARILAMAK
-  JATIPURNO
-  SILALAS
-  SINTUNG
-  GAMBASAN
-  SLAHUNG
-  DUNGUS CARIANG
-  SITUMANDALA
-  KUBUTAMBAHAN
-  TANJUNG DURIAN PASAR BARU
-  JENANG
-  JOMIN BARAT
-  LUBUK NGIN BARU
-  RANCAILAT
-  LERE
-  TEPA
-  PADUKUHAN KRATON
-  DURENJAYA
-  JAPOH
-  WARNASARI
-  PADANG BULAN
-  TUMBUKAN BANYU
-  SAMATE
-  PONCOL
-  TENAJAR KIDUL
-  GULI
-  PENUJAK
-  PAMEGARSARI
-  BARENGLOR
-  CAHAYA MAKMUR
-  KARANGTENGAH
-  MENDAWAI
-  MADUREJO
-  JATITAMBAN
-  TAWALI
-  JONTLAK
-  BONDER
-  GETASREJO
-  CURAHNONGKO
-  LIMUSNUNGGAL
-  PAGADUNGAN
-  CIBUNARJAYA
-  TEBING
-  CIKALANG
-  ASYAMAN
-  HARAPAN MULIA
-  PODOREJO
-  LUMPUE
-  JONGGOL
-  NEPO
-  GEMPOLKURUNG
-  KANAAN
-  CANDI
-  GALAR
-  BRONTOKUSUMAN
-  TANJUNG BULAN
-  SEMBALUN
-  MELAYU
-  PENDOWO
-  ADILUWIH
-  TEJO AGUNG
-  PASONGSONGAN
-  KWANSU
-  CIBALIUNG
-  WRINGINGINTUNG
-  PASAR TANJUNG ENIM
-  NAIMATA
-  SAMAKUROK
-  PARAKANCANGGAH
-  MARGAMULYA
-  ALAI GELOMBANG
-  HAMBALA
-  KUBANG JAYA
-  KALIANGSANA
-  KIJANG KOTA
-  REMA
-  MUKAI PINTU
-  LALUNG
-  HUTABALANG
-  KARANGPAWITAN
-  SELISUN
-  KAWALI
-  SUKOHARJO
-  GADING
-  SUWAWAL
-  SEI SERINDAN
-  KALIBALANGAN
-  PUNGGULAN
-  MARGOMULYO
-  MOJODOYONG
-  BOJONG NANGKA
-  MELONG
-  MARGAHAYU
-  BANGUNSARI
-  TALANG
-  MENGANTI
-  SUDUNGDEWO
-  DANDA JAYA
-  BLANG PULO
-  KEULILEE
-  HALABOLU
-  MERDUATI
-  AWIPARI
-  SIJERUK
-  RIJALI
-  TIKALA
-  PAMUSIAN
-  MEGANG SAKTI I
-  KEMANGGISAN
-  PENGAJARAN
-  SIPISPIS
-  PULUTAN
-  DURJAN
-  SIPAYUNG
-  JANGGAN
-  CINTAMANIK
-  KAPUR
-  NAMBANGAN
-  WLINGI
-  ULAK KARANG SELATAN
-  JADIREJO
-  RUMAH TIGA
-  WASALABOSE
-  CIJULANG

# Sppg per provinsi and ranking

dominasi oleh area sekitar pulau jawa dan sumatera utara serta sulawesi.

paling sedikit di papua dan kalimantan atau area timur indonesia.

In [54]:
sppg_per_provinsi = df['Provinsi SPPG'].value_counts()
print(sppg_per_provinsi)

Provinsi SPPG
JAWA BARAT                    6313
JAWA TENGAH                   4292
JAWA TIMUR                    4017
SUMATERA UTARA                1394
BANTEN                        1315
LAMPUNG                       1147
SULAWESI SELATAN               828
SUMATERA SELATAN               818
NUSA TENGGARA BARAT            815
RIAU                           717
ACEH                           699
DKI JAKARTA                    619
KALIMANTAN BARAT               497
DAERAH ISTIMEWA YOGYAKARTA     442
SUMATERA BARAT                 422
KALIMANTAN SELATAN             291
SULAWESI TENGGARA              275
NUSA TENGGARA TIMUR            274
BALI                           261
KEPULAUAN RIAU                 234
SULAWESI TENGAH                228
KALIMANTAN TIMUR               217
JAMBI                          206
SULAWESI UTARA                 183
SULAWESI BARAT                 180
BENGKULU                       152
MALUKU UTARA                   109
MALUKU                         108
KEPULAUAN BANGKA BELITUNG      104
KALIMANTAN TENGAH              102
GORONTALO                       90
PAPUA                           84
KALIMANTAN UTARA                59
PAPUA BARAT                     49
PAPUA TENGAH                    34
PAPUA BARAT DAYA                33
PAPUA SELATAN                   19
PAPUA PEGUNUNGAN                13
Name: count, dtype: int64

# sppg jawa vs luar pulau jawa

around 56% penduduk indonesia di pulau jawa (https://databoks.katadata.co.id/demografi/statistik/4e9e52829d77f4b/lebih-dari-setengah-penduduk-indonesia-tinggal-di-jawa)

tapi 61% sppg di jawa sedangkan cuman 39% di luar jawa, menurut kepercayaan saya pembukaan sppg di luar jawa simply sulit karena aksesability.

In [55]:
provinsi_jawa = [
    'BANTEN', 'JAWA BARAT', 'DKI JAKARTA', 'JAWA TENGAH',
    'DAERAH ISTIMEWA YOGYAKARTA', 'JAWA TIMUR'
]

df['Wilayah'] = df['Provinsi SPPG'].apply(
    lambda x: 'Pulau Jawa' if any(prov in str(x).upper() for prov in provinsi_jawa) else 'Luar Pulau Jawa'
)

perbandingan = df['Wilayah'].value_counts()
persentase = df['Wilayah'].value_counts(normalize=True) * 100

print("Jumlah Unit SPPG:")
print(perbandingan)
print("\nPersentase Distribusi:")
print(persentase)

Jumlah Unit SPPG:
Wilayah
Pulau Jawa         16998
Luar Pulau Jawa    10642
Name: count, dtype: int64

Persentase Distribusi:
Wilayah
Pulau Jawa         61.497829
Luar Pulau Jawa    38.502171
Name: proportion, dtype: float64

In [56]:
df

,No,Provinsi SPPG,Kab./Kota SPPG,Kecamatan SPPG,Kelurahan/Desa SPPG,Alamat SPPG,Nama SPPG,Wilayah
0,1.0,JAWA TENGAH,KEBUMEN,BUAYAN,ADIWARNO,"Jl. Karangbolong,Adiwarno, Kec. Buayan, Kabup...",SPPG Kebumen Buayan Rangkah,Pulau Jawa
1,2.0,KALIMANTAN SELATAN,TANAH LAUT,TAMBANG ULANG,SUNGAI PINANG,Jl. Kebun Karet H. Abidin Rt 002 Rw 001 Desa ...,SPPG Tanah Laut Tambang Ulang Sungai Pinang,Luar Pulau Jawa
2,3.0,KEPULAUAN RIAU,KOTA BATAM,SAGULUNG,TEMBESI,"Jl Letjen Suprapto, Daerah Mall Top 100 Tembe...",SPPG Kota Batam Sagulung Tembesi 1,Luar Pulau Jawa
3,4.0,JAWA TENGAH,KEBUMEN,PREMBUN,TUNGGALROSO,Desa Tunggalroso Kecamatan Prembun Kabupaten ...,SPPG Kebumen Prembun Tunggalroso,Pulau Jawa
4,5.0,JAWA BARAT,CIANJUR,SUKALUYU,SINDANGRAJA,Jl. Raya Cibogo Bandung Jonggol sindangraja s...,SPPG Cianjur Sukaluyu Sindangraja,Pulau Jawa
...,...,...,...,...,...,...,...,...
27635,27636.0,SUMATERA UTARA,KARO,TIGABINANGA,PERGENDANGEN,"SIMPANG PERGENDANGEN, KECAMATAN TIGA BINANGA,...",SPPG Karo Tiga Binaga Pergendangen,Luar Pulau Jawa
27636,27637.0,JAWA TIMUR,SIDOARJO,SIDOARJO,SIDOKARE,"Ruko Royal Palace, Blok N9, Jl. Sunandar Priy...",SPPG Sidoarjo Sidoarjo Sidokare,Pulau Jawa
27637,27638.0,JAWA BARAT,KOTA BANDUNG,REGOL,CISEUREUH,"JL. PURI DAGO MAS UTAMA NO.65, RT 007/ RW 023",SPPG Kota Bandung Regol Ciseureuh,Pulau Jawa
27638,27639.0,JAWA BARAT,KOTA BOGOR,TANAH SAREAL,SUKADAMAI,"Jl. Seremped Wetan, RT.04/RW.09, Sukadamai, K...",SPPG Kota Bogor Tanah Sareal Sukadamai,Pulau Jawa
27639,27640.0,LAMPUNG,PRINGSEWU,PRINGSEWU,PRINGSEWU SELATAN,"Jl Kartini RT/RW:02/03, Pringsewu Selatan",SPPG Pringsewu Pringsewu Pringsewu Selatan 1,Luar Pulau Jawa